import {useEffect,useState} from 'react';
import {pwmPath} from '../lib/pwm.mjs';

export function CPULab(){
  const [step,setStep]=useState(0),[play,setPlay]=useState(false);
  useEffect(()=>{if(!play)return;const timer=setInterval(()=>setStep(s=>(s+1)%4),1500);return()=>clearInterval(timer);},[play]);
  const steps=['取指','译码','执行','外设更新'];
  const explanations=['从 Flash 中读取下一条机器指令。程序计数器指向它的位置。','解码器识别“写外设寄存器”的操作与操作数。','CPU 通过总线发出写事务，将一个位设为 1。','GPIO 输出锁存更新，推挽电路输出高电平（假设高电平点亮 LED）。'];
  return <section className="lab"><span className="eyebrow">实验 01 / MCU</span><h2>代码怎样走到引脚</h2><div className="flow-steps">{steps.map((s,i)=><div key={s} className={i===step?'active':''}>{i+1}. {s}</div>)}</div><p aria-live="polite" className="answer">{explanations[step]}</p><svg viewBox="0 0 700 170" role="img" aria-label={step===3?'LED 已点亮':'LED 尚未更新'}><rect x="30" y="40" width="170" height="90" rx="14" fill="#dbeafe"/><text x="115" y="92" textAnchor="middle" fill="#12385e">CPU / 总线写入</text><path d="M200 85H400" stroke="#6180a8" strokeWidth="5"/><rect x="400" y="40" width="120" height="90" rx="14" fill="#e2e8f0"/><text x="460" y="92" textAnchor="middle" fill="#12385e">GPIO</text><path d="M520 85H590" stroke="#6180a8" strokeWidth="5"/><circle cx="625" cy="85" r="30" fill={step===3?'#f4ba36':'#64748b'}/></svg><div className="toolbar"><button onClick={()=>{setPlay(false);setStep(s=>(s+1)%4);}}>下一步</button><button onClick={()=>setPlay(p=>!p)}>{play?'暂停':'自动播放'}</button><button onClick={()=>{setPlay(false);setStep(0);}}>重新开始</button></div><p className="note">为教学将过程拆成四步，不是周期精确的 Cortex-M3 仿真，也没有执行真实 C 代码。</p><Quiz question="写寄存器前，C 文本首先需要什么？" options={['编译、链接为机器代码','直接把文字送到引脚']} correct={0} explanation="CPU 执行机器指令；源码需先经过工具链处理。"/></section>
}

export function GPIOLab(){
  const [mode,setMode]=useState('pp'),[bit,setBit]=useState(true),[pull,setPull]=useState(true),[duty,setDuty]=useState(50);
  const level=mode==='pp'?(bit?'高':'低'):(!bit?'低':pull?'高':'不确定（高阻）');
  const wave=pwmPath(duty);
  return <section className="lab"><span className="eyebrow">实验 02 / GPIO & PWM</span><h2>先看谁驱动，再看怎样驱动</h2><div className="toolbar"><label>输出类型 <select value={mode} onChange={e=>setMode(e.target.value)} aria-label="输出类型"><option value="pp">通用推挽</option><option value="od">通用开漏</option></select></label><label><input type="checkbox" checked={bit} onChange={e=>setBit(e.target.checked)}/> 写入 1</label><label><input type="checkbox" checked={pull} onChange={e=>setPull(e.target.checked)}/> 外部上拉</label></div><p className="answer" aria-live="polite">引脚电平：<strong>{level}</strong>。{mode==='pp'?'推挽主动选择高或低。':bit?'开漏释放，电平由外部电路决定。':'开漏晶体管导通，主动拉低。'}</p><h3>PWM：改变高电平持续时间</h3><label>占空比 <output>{duty}%</output><input aria-label="PWM 占空比" type="range" min="0" max="100" value={duty} onChange={e=>setDuty(Number(e.target.value))}/></label><svg viewBox="0 0 700 200" role="img" aria-label={`占空比 ${duty}% 的理想 PWM 波形`}><path d="M20 30V160H680" stroke="#8a9bb1" fill="none"/><path d={wave} stroke="#17a68a" strokeWidth="4" fill="none"/><text x="25" y="25" fill="#6b849e">高电平幅度固定</text><text x="475" y="187" fill="#6b849e">4 个周期 · 每周期 1 ms</text></svg><p>频率固定为 1 kHz，高电平时间 {(duty/100).toFixed(2)} ms。复用推挽时，由定时器比较器产生这个信号。图为理想波形，不模拟上升沿、电容或电机动态。</p><p className="note">原代码 ARR=999 且限制 CCR≤999，所以最高为 99.9%；这里 100% 是理想持续高电平，不能直接照搬为原函数参数。</p><Quiz question="开漏写 1 且没有任何上拉，会怎样？" options={['保证 3.3 V','释放输出，电平不确定','保证 0 V']} correct={1} explanation="开漏不能主动拉高。释放后需要外部电路建立确定电平。"/></section>
}

export function AILab(){
  const [weight,setWeight]=useState(1),[bias,setBias]=useState(-.2),[word,setWord]=useState('action');
  const z=weight*.6-.5*.2+bias,value=1/(1+Math.exp(-z));
  const descriptions:Record<string,string>={act:'act：行动；行为。与拉丁语 actus / agere 的相关形式有历史联系。',action:'action：行动、行为、作用。经法语和拉丁语 āctiō 等形式进入英语，追溯到 agere。',active:'active：活跃的、主动的。经法语和拉丁语 activus 等形式，关联 actus / agere。'};
  return <section className="lab"><span className="eyebrow">实验 04 / AI & LANGUAGE</span><h2>一个神经元，两个可调参数</h2><p>固定 x₁=0.6、x₂=0.2、w₂=−0.5。这里只做推理，没有训练模型。</p><div className="control-grid"><label>w₁ 权重 <output>{weight.toFixed(1)}</output><input aria-label="神经元权重" type="range" min="-5" max="5" step=".1" value={weight} onChange={e=>setWeight(Number(e.target.value))}/></label><label>b 偏置 <output>{bias.toFixed(1)}</output><input aria-label="神经元偏置" type="range" min="-3" max="3" step=".1" value={bias} onChange={e=>setBias(Number(e.target.value))}/></label></div><p className="answer">z = {weight.toFixed(1)} × 0.6 − 0.5 × 0.2 + ({bias.toFixed(1)}) = {z.toFixed(3)}<br/>sigmoid(z) = <strong>{value.toFixed(4)}</strong></p><svg viewBox="0 0 600 80" role="img" aria-label={`神经元输出 ${value.toFixed(4)}`}><rect x="10" y="15" width="580" height="32" rx="10" fill="#dbe4ef"/><rect x="10" y="15" width={580*value} height="32" rx="10" fill="#17a68a"/><text x="10" y="73" fill="#6b849e">0</text><text x="580" y="73" fill="#6b849e">1</text></svg><button onClick={()=>{setWeight(1);setBias(-.2);}}>重置神经元</button><h2>同源词，为什么不等于同义词？</h2><p>点击词卡，观察共同来源与词性差异。下面是人工整理的词源教学数据，不是词向量计算结果。</p><div className="word-cards">{['act','action','active'].map(w=><button key={w} aria-pressed={word===w} onClick={()=>setWord(w)}><b>act</b>{w.slice(3)}</button>)}</div><p className="answer" aria-live="polite">{descriptions[word]}</p><p>共同追溯线索：拉丁语 agere（做、使动）及相关形式。高亮 act 仅作词族记忆；不是完整历史路线，也不代表模型实际 Token 边界。</p><p className="note">依据 Merriam-Webster 的 act、action、active 词源条目；具体借入路线不同。模型相似度不能验证词源亲缘。</p><Quiz question="action 和 active 来自相关词源，能说明什么？" options={['任何语境都能互换','所有模型都会把它们切成 act + 后缀','有历史联系，但词义、词性和分词结果仍需分别判断']} correct={2} explanation="词源关系、现代语义和模型编码是三个不同层面。"/></section>
}

function Quiz({question,options,correct,explanation}:{question:string;options:string[];correct:number;explanation:string}){
  const [answer,setAnswer]=useState<number|null>(null);
  return <div><h3>检查理解</h3><p>{question}</p><div className="toolbar">{options.map((o,i)=><button key={o} onClick={()=>setAnswer(i)}>{o}</button>)}</div>{answer!==null&&<p className="answer" role="status">{answer===correct?'回答正确。':'再想一想。'}{explanation}</p>}</div>
}
